global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-api:4000']

  - job_name: 'postgres-db'
    scrape_interval: 10s
    static_configs:
      - targets: ['postgres-db:5432']

  - job_name: 'redis-cache'
    scrape_interval: 10s
    static_configs:
      - targets: ['redis-cache:6379']
